# Use postgres/example user/password credentials
version: '3.1'

services:
  app_database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  app_backend:
    build: ./backend
    environment:
      DB_SERVER: app_backend
    depends_on:
      - app_database
    ports:
      - 8989:8080
    links:
      - "app_database"

  app_frontend:
    build: ./app
    depends_on:
      - app_backend
    ports:
      - 3001:3000
    links:
      - "app_backend"
