version: '3.1'

services:

  app_database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

  app_backend:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  app_client:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
